# Neck
- type: loadoutGroup
  parent: CommonCollars
  id: BartenderNeck
  name: loadout-group-bartender-neck
  minLimit: 0

- type: loadoutGroup
  parent: CommonCollars
  id: BotanistNeck
  name: loadout-group-botanist-neck
  minLimit: 0

- type: loadoutGroup
  parent: CommonCollars
  id: ChefNeck
  name: loadout-group-chef-neck
  minLimit: 0

- type: loadoutGroup
  parent: CommonCollars
  id: JanitorNeck
  name: loadout-group-janitor-neck
  minLimit: 0

- type: loadoutGroup
  parent: CommonCollars
  id: ServiceWorkerNeck
  name: loadout-group-service-worker-neck
  minLimit: 0

# Jumpsuits
- type: loadoutGroup
  id: ServiceWorkerJumpsuit
  name: loadout-group-service-worker-jumpsuit
  loadouts:
  - BartenderJumpsuit
  - BartenderJumpskirt
  - BartenderJumpsuitPurple
  - ChefJumpsuit
  - ChefJumpskirt

# Shoes
- type: loadoutGroup
  id: BartenderShoes
  name: loadout-group-bartender-shoes
  minLimit: 0
  defaultSelected: 1
  loadouts:
  - BlackShoes

- type: loadoutGroup
  id: BotanistShoes
  name: loadout-group-botanist-shoes
  minLimit: 0
  defaultSelected: 1
  loadouts:
  - BrownShoes

- type: loadoutGroup
  id: ChefShoes
  name: loadout-group-chef-shoes
  minLimit: 0
  defaultSelected: 1
  loadouts:
  - BlackShoes
  - ClothingShoesChef

- type: loadoutGroup
  id: JanitorShoes
  name: loadout-group-janitor-shoes
  minLimit: 0
  defaultSelected: 1
  loadouts:
  - Galoshes

- type: loadoutGroup
  id: ServiceWorkerShoes
  name: loadout-group-service-worker-shoes
  minLimit: 0
  defaultSelected: 1
  loadouts:
  - BlackShoes
  - ClothingShoesChef
