using System.Linq;
using Content.Shared.Body;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class MarkingPicker : Control
{
    private MarkingsViewModel? _markingsModel;

    public MarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UpdateMarkings();
    }

    public void SetModel(MarkingsViewModel model)
    {
        _markingsModel = model;

        _markingsModel.OrganDataChanged += UpdateMarkings;
        _markingsModel.EnforcementsChanged += UpdateMarkings;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel?.OrganDataChanged += UpdateMarkings;
        _markingsModel?.EnforcementsChanged += UpdateMarkings;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel?.OrganDataChanged -= UpdateMarkings;
        _markingsModel?.EnforcementsChanged -= UpdateMarkings;
    }

    private void UpdateMarkings()
    {
        if (_markingsModel is null)
            return;
        
        if (OrganTabs.ChildCount > 0)
            OrganTabs.CurrentTab = 0;
        
        var organTabs = OrganTabs.Children.ToList();
        OrganTabs.RemoveAllChildren();
        
        var (toAdd, toRemove) =
            GetOrganTabChanges(_markingsModel.OrganData, organTabs, _markingsModel);

        foreach (var tab in toRemove)
            organTabs.Remove(tab);

        foreach (var (organ, organData) in toAdd)
        {
            var control = new OrganMarkingPicker(_markingsModel, organ, organData.Layers, organData.Group);
            if (control.Empty)
                continue;

            organTabs.Add(control);
        }
    
        foreach (var (organ, _) in _markingsModel.OrganData)
        {
            var control = organTabs
                .OfType<OrganMarkingPicker>()
                .FirstOrDefault(x => x.Organ == organ);

            if (control is null)
                continue;
            
            OrganTabs.AddChild(control);
            OrganTabs.SetTabTitle(OrganTabs.ChildCount - 1, Loc.GetString($"markings-organ-{organ.Id}"));
        }
        
        if (OrganTabs.ChildCount > 0)
            OrganTabs.CurrentTab = 0;
        OrganTabs.TabsVisible = OrganTabs.ChildCount > 1;
    }

    private (
        Dictionary<ProtoId<OrganCategoryPrototype>, OrganMarkingData> ToAdd,
        List<OrganMarkingPicker> ToRemove)
        GetOrganTabChanges(
            Dictionary<ProtoId<OrganCategoryPrototype>, OrganMarkingData> organData,
            List<Control> organTabs,
            MarkingsViewModel markingsModel)
    {
        var toAdd = new Dictionary<ProtoId<OrganCategoryPrototype>, OrganMarkingData>(organData);
        var toRemove = new List<OrganMarkingPicker>();

        foreach (var control in organTabs)
        {
            if (control is not OrganMarkingPicker organTab)
                continue;

            var found = false;

            foreach (var (organ, data) in organData)
            {
                if (!organTab.Equals(markingsModel, organ, data.Layers, data.Group))
                    continue;

                toAdd.Remove(organ);
                found = true;
                break;
            }

            if (!found)
                toRemove.Add(organTab);
        }

        return (toAdd, toRemove);
    }
}