using System.Linq;
using Content.Shared.Body;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class OrganMarkingPicker : Control
{
    [Dependency] private MarkingManager _marking = default!;
    [Dependency] private IEntityManager _entity = default!;

    private readonly SpriteSystem _sprite;

    private readonly MarkingsViewModel _markingsModel;
    private readonly HashSet<HumanoidVisualLayers> _layers;
    private readonly ProtoId<MarkingsGroupPrototype> _group;
    private readonly ProtoId<OrganCategoryPrototype> _organ;

    public ProtoId<OrganCategoryPrototype> Organ => _organ;

    public OrganMarkingPicker(MarkingsViewModel markingsModel, ProtoId<OrganCategoryPrototype> organ, HashSet<HumanoidVisualLayers> layers, ProtoId<MarkingsGroupPrototype> group)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _markingsModel = markingsModel;
        _layers = layers;
        _group = group;
        _organ = organ;

        _sprite = _entity.System<SpriteSystem>();

        UpdateMarkings();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel.OrganProfileDataChanged += OnOrganProfileDataChanged;
        _markingsModel.EnforcementsChanged += UpdateMarkings;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel.OrganProfileDataChanged -= OnOrganProfileDataChanged;
        _markingsModel.EnforcementsChanged -= UpdateMarkings;
    }

    public bool Empty => LayerTabs.ChildCount == 0;

    private void OnOrganProfileDataChanged(bool refresh)
    {
        if (refresh)
            UpdateMarkings();
    }

    private void UpdateMarkings()
    {
        if (!_markingsModel.OrganProfileData.TryGetValue(_organ, out var organProfileData))
            return;

        var layerTabs = LayerTabs.Children.ToList();
        LayerTabs.RemoveAllChildren();

        var (toAdd, toRemove) =
            GetLayerTabChanges(_layers, layerTabs, _markingsModel);

        foreach (var tab in toRemove)
            layerTabs.Remove(tab);

        foreach (var layer in toAdd)
        {
            var allMarkings =
                _markingsModel.EnforceGroupAndSexRestrictions
                    ? _marking.MarkingsByLayerAndGroupAndSex(layer, _group, organProfileData.Sex)
                    : _marking.MarkingsByLayer(layer);

            if (allMarkings.Count == 0)
                continue;

            layerTabs.Add(new LayerMarkingPicker(_markingsModel, _organ, layer, allMarkings));
        }

        foreach (var layer in _layers)
        {
            var control = layerTabs
                .OfType<LayerMarkingPicker>()
                .FirstOrDefault(x => x.Equals(_organ, layer, _markingsModel.EnforceGroupAndSexRestrictions));

            if (control is null)
                continue;

            LayerTabs.AddChild(control);

            if (Loc.TryGetString($"markings-layer-{layer}-{_group.Id}", out var layerTitle))
                LayerTabs.SetTabTitle(LayerTabs.ChildCount - 1, layerTitle);
            else
                LayerTabs.SetTabTitle(LayerTabs.ChildCount - 1, Loc.GetString($"markings-layer-{layer}"));
        }

        LayerTabs.TabsVisible = LayerTabs.ChildCount > 1;
    }

    private (
        List<HumanoidVisualLayers> ToAdd,
        List<LayerMarkingPicker> ToRemove)
        GetLayerTabChanges(
            HashSet<HumanoidVisualLayers> layers,
            List<Control> layerTabs,
            MarkingsViewModel markingsModel)
    {
        var toAdd = new List<HumanoidVisualLayers>(layers);
        var toRemove = new List<LayerMarkingPicker>();

        foreach (var control in layerTabs)
        {
            if (control is not LayerMarkingPicker layerTab)
                continue;

            var found = false;

            foreach (var layer in layers)
            {
                if (!layerTab.Equals(
                        _organ,
                        layer,
                        markingsModel.EnforceGroupAndSexRestrictions))
                    continue;

                toAdd.Remove(layer);
                found = true;
                break;
            }

            if (!found)
                toRemove.Add(layerTab);
        }

        return (toAdd, toRemove);
    }
    
    public bool Equals(MarkingsViewModel markingsModel, ProtoId<OrganCategoryPrototype> organ,
        HashSet<HumanoidVisualLayers> layers, ProtoId<MarkingsGroupPrototype> group) => 
        _markingsModel == markingsModel
        && _layers.SetEquals(layers)
        && _group == group
        && _organ == organ;
}