# For mantles
- type: loadoutEffectGroup
  id: MasterHoS
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 20h

# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuit
  groupBy: HoSGear # FLOOF
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS

- type: loadout
  id: HeadofSecurityJumpskirt
  groupBy: HoSGear # FLOOF
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS

- type: loadout
  id: HeadofSecurityTurtleneck
  groupBy: HoSGear # FLOOF
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: HeadofSecurityTurtleneckSkirt
  groupBy: HoSGear # FLOOF
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: HeadofSecurityFormalSuit
  groupBy: HoSGear # FLOOF
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal

- type: loadout
  id: HeadofSecurityFormalSkirt
  groupBy: HoSGear # FLOOF
  equipment:
    jumpsuit: ClothingUniformJumpskirtHosFormal

# Head
- type: loadout
  id: HeadofSecurityHead
  groupBy: HoSGear # FLOOF
  equipment:
    head: ClothingHeadHatHoshat

- type: loadout
  id: HeadofSecurityBeret
  groupBy: HoSGear # FLOOF
  equipment:
    head: ClothingHeadHatBeretHoS

# Neck
- type: loadout
  id: HeadofSecurityCloak
  groupBy: HoSGear # FLOOF
  equipment:
    neck: ClothingNeckCloakHos

- type: loadout
  id: HeadofSecurityMantle
  groupBy: HoSGear # FLOOF
  equipment:
    neck: ClothingNeckMantleHOS
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: startingGear
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS

# OuterClothing
- type: loadout
  id: HeadofSecurityCoat
  groupBy: HoSGear # FLOOF
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout
  id: HeadofSecurityWinterCoat
  groupBy: HoSGear # FLOOF
  equipment:
    outerClothing: ClothingOuterWinterHoS
